version: "3.4"
services:
  beacon:
    image: "beacon.lighthouse-prater:mgarciate"
    build:
      context: beacon
      args:
        UPSTREAM_VERSION: v2.1.3
    volumes:
      - "beacon-data:/root/.lighthouse"
    ports:
      - "9000"
    restart: unless-stopped
    environment:
      BEACON_API_PORT: "3500"
      HTTP_WEB3PROVIDER: "http://goerli-geth.dappnode:8545"
      CORSDOMAIN: "http://lighthouse.dappnode"
      CHECKPOINT_SYNC_URL: "http://beacon-chain.prysm-prater.dappnode:4000"
      EXTRA_OPTS: ""
  validator:
    image: "validator.lighthouse-prater:mgarciate"
    build:
      context: validator
      args:
        UPSTREAM_VERSION: v2.1.3
    command: ["--http"]
    volumes:
      - "validator-data:/root/.lighthouse"
      - "validator-public-keys:/root/public-keys"
    restart: unless-stopped
    environment:
      HTTP_WEB3SIGNER: "http://web3signer:9003"
      BEACON_NODE_ADDR: "http://beacon:3500"
      GRAFFITI: validating_from_DAppNode
      DEFAULT_VALIDATOR_PUBLIC_KEY: ""
    ports:
      - "5062:5062"
  web3signer:
    build:
      context: web3signer
      args:
        UPSTREAM_VERSION: 21.10.5
    image: consensys/web3signer:mgarciate
    command: ["--key-store-path=/keyfiles",
            "--http-listen-port=9003",
            "--http-listen-host=0.0.0.0",
            "--http-host-allowlist=*",
            "eth2",
            "--slashing-protection-enabled=false",
            "--network=prater"]
    volumes:
      - $PWD/keyfiles:/keyfiles
    ports:
      - "9003:9000"
volumes:
  beacon-data: {}
  validator-data: {}
  validator-public-keys: {}
